DBT-1314: Demo/recording
vocali-genesis/admin-portal pull request #8
Opened 2024-07-11 17:33 UTC by Mrtn-Omwenga

This branch focused on preparing dashboard and recording pages for demo. Some progress was made on refactoring the code.

2024-07-11 18:38 UTC, abelbordonado commented on core/components/sidebar.tsx
> +          {" "}
🐌

2024-07-11 18:39 UTC, abelbordonado commented on core/components/styles/nav.module.css
> +  background-color: #1C364B;
Ask @deevannaveed  to implement SCSS and helo you make a palette of colors

2024-07-11 18:40 UTC, abelbordonado commented on core/components/styles/sidebar.module.css
> +  display: none;
There is tailwind for this  https://tailwindcss.com/docs/display 

Display none, flex, all this "positioning" styles are good to use for flex.

2024-07-11 18:42 UTC, abelbordonado commented on core/components/styles/sidebar.module.css
>  @media (max-width: 500px) {
Is this media standard

Doublecheck 
![Uploading image.png…]()

2024-07-11 18:42 UTC, abelbordonado commented on core/components/styles/sidebar.module.css
> +    font-family: "Montserrat", sans-serif;
Font family shall be in global? or is for all the buttons?

2024-07-11 18:43 UTC, abelbordonado commented on core/components/sidebar.tsx
> +      <div className={sidebar_styles.bottomButtons}>
This button shall go in resources

We can have nav-button
nav-accent-button

2024-07-11 18:46 UTC, abelbordonado commented on pages/auth/[slug].tsx
> +        </div>
Lets extract this into a sub function (can be in the same file)  So is more readable.

2024-07-11 18:49 UTC, abelbordonado commented
<img width="342" alt="image" src="https://github.com/user-attachments/assets/029cddea-c2d2-414b-bd54-42add88b206d">

2024-07-11 18:50 UTC, abelbordonado commented
<img width="675" alt="image" src="https://github.com/user-attachments/assets/a85b1014-5b05-428e-a603-863ad515c64e">

2024-07-11 18:52 UTC, abelbordonado commented
If I make a record, and I reload the page. I see a black page that says `resource not found` 
We can create a full screen component. (in resources, called `loader` to show in this scenarios) 
And another for not found (We can make a component not found no need to be full page) that we can use in other places

2024-07-11 18:54 UTC, abelbordonado commented
<img width="603" alt="image" src="https://github.com/user-attachments/assets/beaf2a07-5d96-4c8b-9fa8-9a0ab356748f">

2024-07-11 18:55 UTC, abelbordonado commented
<img width="638" alt="image" src="https://github.com/user-attachments/assets/db7f5d79-fa82-4a43-9073-fea883aaa109">

2024-07-11 18:58 UTC, abelbordonado commented
<img width="615" alt="image" src="https://github.com/user-attachments/assets/2e6c3c56-38f5-48a0-b3a7-16343bfa1dcc">


<img width="506" alt="image" src="https://github.com/user-attachments/assets/f40354e0-3c1b-4808-b733-2552bb304bec">

2024-07-11 18:59 UTC, abelbordonado requested changes
Great Job! 👏👏👏

2024-07-12 14:32 UTC, Mrtn-Omwenga commented on core/components/styles/sidebar.module.css
> +    font-family: "Montserrat", sans-serif;
Not for all components. Some are a different font

2024-07-12 14:33 UTC, Mrtn-Omwenga commented on pages/auth/[slug].tsx
> +        </div>
But this is only used in one file?

2024-07-12 14:53 UTC, Mrtn-Omwenga commented on core/components/styles/sidebar.module.css
>  @media (max-width: 500px) {
I used this because any less the components look very cramped.

2024-07-15 09:08 UTC, abelbordonado commented
Client feedback:

When we are recording, on click again, instead of complete we have 2 buttons: Stop or Continue (in case we just want to pause)

2024-07-15 09:08 UTC, abelbordonado commented
Client Feedback:  Before any DELETE button we need a Confirm Pop Up , not directly delete

2024-07-15 09:23 UTC, abelbordonado commented
Allow to select the microphone (I know this is a new requirement) 
Show the sound wave when they talk so the user knows is recording

2024-07-15 11:17 UTC, abelbordonado commented on core/components/styles/sidebar.module.css
> +  display: none;
Separated task https://www.notion.so/tianlu/Use-SCSS-and-sync-all-the-hardcode-colores-and-documented-c72c7e12a1e9439b9bcc5bac020dcf8a?pvs=4

2024-07-22 13:07 UTC, merged

2024-07-22 15:41 UTC, abelbordonado commented
<img width="641" alt="image" src="https://github.com/user-attachments/assets/76124710-736b-4928-9647-79ffc12c232b">

2024-07-22 15:42 UTC, abelbordonado commented
<img width="648" alt="image" src="https://github.com/user-attachments/assets/951305c4-41c4-48bf-aa04-8a353ab38cc6">

2024-07-22 15:42 UTC, abelbordonado commented
<img width="233" alt="image" src="https://github.com/user-attachments/assets/43e6e692-34dd-4183-a360-327b19da00ae">

2024-07-22 15:43 UTC, abelbordonado commented
<img width="894" alt="image" src="https://github.com/user-attachments/assets/4d07eebc-7057-433c-a894-dc2893109782">